<?php
/* Generated by PhpTranspiler pt.0.59. Source: basic.input.ts. */
final class Greeter {
  public readonly string $name;
  public function __construct(string $name) {
    $this->name = $name;
  }
  public function message(): string {
    return "Hello {$this->name}";
  }
}
