<?php
/* Generated by PhpTranspiler pt.0.59. Source: collections.input.ts. */
final class CollectionPresenter {
  public function summarize(array $values, string $needle): string {
    $count = count($values);
    $found = in_array($needle, $values, true);
    $labels = implode(", ", $values);
    $tail = array_slice($values, 1);
    $items = [];
    $items[] = $needle;
    return $labels;
  }
}
