<?php
/* Generated by PhpTranspiler pt.0.59. Source: control.input.ts. */
final class ControlFlow {
  public function normalize(string $label, string $fallback): string {
    $trimmed = trim($label);
    $lowered = mb_strtolower($trimmed);
    if ($lowered === "") {
      return $fallback;
    }
    return $lowered;
  }
  public function fail(string $message): void {
    throw new Exception($message);
  }
}
