<?php
/* Generated by PhpTranspiler pt.0.59. Source: functional.input.ts. */
final class FunctionalCollections {
  public function clean(array $values): array {
    $trimmed = array_map(fn($value) => trim($value), $values);
    $present = array_values(array_filter($trimmed, fn($value) => $value !== ""));
    $output = [];
    foreach ($present as $value) {
      $output[] = $value;
    }
    return $output;
  }
}
