<?php
/* Generated by PhpTranspiler pt.0.59. Source: functions.input.ts. */
function normalizeName(string $value): string {
  return mb_strtolower(trim($value));
}
interface Writer {
  public function configured(): bool;
  public function saveContent(string $path, string $bytes, string $message): void;
  public function fail(string $message): never;
}
final class UserRecord {
  public readonly string $name;
  public function __construct(string $name) {
    $this->name = $name;
  }
}
final class FunctionUsage {
  public function make(string $value, bool $enabled): UserRecord {
    if (!$enabled) {
      return new UserRecord("disabled");
    }
    $normalized = normalizeName($value);
    return new UserRecord($normalized);
  }
}
final class NullWriter implements Writer {
  public function configured(): bool {
    return false;
  }
  public function saveContent(string $path, string $bytes, string $message): void {
    throw new RuntimeException("Gitプロバイダーが未設定です。");
  }
  public function fail(string $message): never {
    throw new RuntimeException($message);
  }
}
