<?php
/* Generated by PhpTranspiler pt.0.59. Source: guards.input.ts. */
final class GuardPayload {
  public readonly string $name;
  public function __construct(string $name) {
    $this->name = $name;
  }
}
final class Guards {
  public function valid(mixed $value, mixed $payload): bool {
    if (is_string($value) && $payload instanceof GuardPayload) {
      return true;
    }
    if (is_array($value)) {
      return true;
    }
    return $value !== null && is_string($payload["name"]);
  }
  public function numeric(mixed $value): bool {
    return (is_int($value) || is_float($value));
  }
}
