<?php
/* Generated by PhpTranspiler pt.0.59. Source: indexing.input.ts. */
final class Indexing {
  public function add(array $values, int|float $index): int|float {
    $total = $values[$index];
    $total += $values[0];
    $values[$index] = $total;
    $values[$index] += 1;
    return $values[$index];
  }
  public function pick(array $payload, string $key): string {
    return $payload[$key] ?? $payload["fallback"];
  }
}
