<?php
/* Generated by PhpTranspiler pt.0.59. Source: literals.input.ts. */
final class LiteralBuilder {
  public function build(string $name, int|float $count): mixed {
    $names = [$name, "fixed"];
    $payload = ['name' => $name, 'count' => $count, 'enabled' => true];
    return $payload;
  }
  public function dottedPath(string $root): string {
    return $root . "/auth.json";
  }
}
