<?php
/* Generated by PhpTranspiler pt.0.59. Source: loops.input.ts. */
final class LoopCounter {
  public function total(array $values): int|float {
    $total = 0;
    for ($index = 0; $index < count($values); $index++) {
      $total = $total;
    }
    return $total;
  }
}
