<?php
/* Generated by PhpTranspiler pt.0.59. Source: migration.input.ts. */
final class MigrationRecordTool {
  public readonly string $prefix;
  public function __construct(string $prefix) {
    $this->prefix = $prefix;
  }
  public function normalize(mixed $input, mixed $record): string {
    $raw = (string)($input);
    $id = (int)($record["id"]);
    $amount = (float)($record["amount"]);
    $enabled = (bool)($record["enabled"]);
    $score = (float)($record["score"]);
    if (str_starts_with($raw, "ad") && str_ends_with($this->prefix, "-")) {
      $record["slug"] = mb_strtolower(trim($raw));
    }
    if (is_int($id) && is_finite($amount)) {
      $record["enabled"] = $enabled;
      $record["score"] = $score;
    }
    unset($record["temp"]);
    unset($record["draft"]);
    return trim($this->prefix);
  }
  public function countEntries(mixed $record): int|float {
    $entries = array_map(fn($key, $value) => [$key, $value], array_keys($record), array_values($record));
    return count($entries);
  }
}
