<?php
/* Generated by PhpTranspiler pt.0.59. Source: object-utils.input.ts. */
final class ObjectUtilities {
  public function keys(array $payload, string $fallback = "none"): array {
    $keys = array_keys($payload);
    if (count($keys) === 0) {
      return [$fallback];
    }
    return $keys;
  }
  public function values(array $payload): array {
    $values = array_values($payload);
    return $values;
  }
}
