<?php
/* Generated by PhpTranspiler pt.0.59. Source: object-access.input.ts. */
final class ObjectAccess {
  public function __construct(private readonly mixed $runtime) {
  }
  public function normalize(array $payload, string $fallback): string {
    if ($payload["kind"] === "draft" && $payload["title"] !== "") {
      $payload["title"] = trim($payload["title"]);
    }
    $label = $payload["title"] !== "" ? $payload["title"] : $fallback;
    return $payload["enabled"] === "true" ? $label : $fallback;
  }
  public function nestedMethod(): string {
    return $this->runtime->serverSideClient->requestMethod();
  }
  public function nestedProperty(): string {
    return $this->runtime->config->updateRepository;
  }
  public function localRuntime(mixed $runtime): string {
    $runtime->serverSideClient->ensureUnlocked();
    return $runtime->configRoot . "/site.json";
  }
  public function localFacade(mixed $serverSideClient, mixed $serverSide, string $path): void {
    $serverSideClient->assertContentPath($path);
    $serverSide->validateContent($path, "");
  }
}
