<?php
/* Generated by PhpTranspiler pt.0.59. Source: runtime.input.ts. */
final class RuntimeHelpers {
  public function encode(string $value, int|float $amount): string {
    $rounded = round($amount);
    $payload = json_encode($value, JSON_UNESCAPED_UNICODE);
    $parts = explode("-", $value);
    $first = mb_substr($value, 0, 1);
    $renamed = str_replace("a", "b", $value);
    return $payload;
  }
}
