<?php
/* Generated by PhpTranspiler pt.0.59. Source: server-foundation.input.ts. */
declare(strict_types=1);
namespace AdlaireStudio;
use ServerSideLogicFoundationSystem\ServerSideLogicFoundationSystemInternal;
final class AuthRuntime {
  public const INITIAL_ADMIN_USERNAME = "admin";
  private const PASSWORD_MIN_LENGTH = 12;
  public function __construct(private readonly string $authFile, private readonly string $stateFile) {
    if (session_status() !== PHP_SESSION_ACTIVE) {
      session_name("adlaire_studio");
      session_start();
    }
  }
  public function ensureInitialAdmin(): void {
    if (is_file($this->authFile)) {
      return;
    }
    $passwordHash = password_hash(AuthRuntime::INITIAL_ADMIN_USERNAME, PASSWORD_DEFAULT);
    if ($passwordHash === false) {
      throw new RuntimeException("初期管理者パスワードをハッシュ化できません。");
    }
    $createdAt = gmdate(DATE_ATOM);
    $payloadData = ['username' => AuthRuntime::INITIAL_ADMIN_USERNAME, 'password_hash' => $passwordHash, 'created_at' => $createdAt, ];
    $payload = json_encode($payloadData, JSON_UNESCAPED_UNICODE);
    if (file_put_contents($this->authFile, $payload, LOCK_EX) === false) {
      throw new RuntimeException("認証情報を書き込めません。");
    }
    chmod($this->authFile, 384);
  }
  public function passwordAllowed(string $password): bool {
    if (strlen($password) < AuthRuntime::PASSWORD_MIN_LENGTH) {
      return false;
    }
    return preg_match("/[A-Za-z]/", $password) === 1 && preg_match("/[0-9]/", $password) === 1;
  }
  public function readState(): mixed {
    if (!is_file($this->stateFile)) {
      return ['failures' => 0, 'locked_until' => 0];
    }
    $bytes = file_get_contents($this->stateFile);
    if ($bytes === false) {
      return ['failures' => 0, 'locked_until' => 0];
    }
    $data = json_decode($bytes, true);
    if (!is_array($data["users"])) {
      return ['failures' => 0, 'locked_until' => 0];
    }
    return $data;
  }
}
final class ServerFoundationFacade {
  public function __construct(private readonly AuthRuntime $auth) {
  }
  public function boot(): void {
    $this->auth->ensureInitialAdmin();
  }
  public function passwordAllowed(string $password): bool {
    return $this->auth->passwordAllowed($password);
  }
  public function apply(string $value): string {
    return (new ServerFoundationWorker($value))->run();
  }
}
final class ServerFoundationWorker {
  public function __construct(private readonly string $value) {
  }
  public function run(): string {
    return trim($this->value);
  }
}
if (!defined('ADLAIRE_STUDIO_NO_RUN')) {
    Bootstrap::run(__DIR__);
}
