<?php
/* Generated by PhpTranspiler pt.0.59. Source: server-collections.input.ts. */
final class ServerCollectionsBridge {
  public function visibleEntries(mixed $entries): mixed {
    $values = array_values($entries);
    $ignored = [".", ".."];
    return array_values(array_diff($values, $ignored));
  }
  public function mergePayload(mixed $base, mixed $extra): mixed {
    return array_merge($base, $extra);
  }
  public function query(mixed $params): string {
    return http_build_query($params);
  }
  public function checksumHead(string $bytes): string {
    $token = strtok($bytes, " \t");
    return (string)($token);
  }
  public function runtimeVersion(): string {
    return PHP_VERSION;
  }
  public function compareVersions(string $left, string $right): int|float {
    return version_compare($left, $right);
  }
  public function sortReleases(mixed $items): mixed {
    usort($items, fn(array $a, array $b): int => version_compare((string)($b["version"] ?? ''), (string)($a["version"] ?? '')));
    return $items;
  }
}
