<?php
/* Generated by PhpTranspiler pt.0.59. Source: server-runtime.input.ts. */
final class ServerRuntimeBridge {
  public const CSRF_KEY = "csrf";
  public function requestMethod(): string {
    $raw = ($_SERVER["REQUEST_METHOD"] ?? "GET");
    $method = (string)($raw);
    return mb_strtoupper($method);
  }
  public function csrfToken(): string {
    if (!isset($_SESSION[ServerRuntimeBridge::CSRF_KEY])) {
      $bytes = random_bytes(32);
      $token = hash("sha256", (string)($bytes));
      $_SESSION[ServerRuntimeBridge::CSRF_KEY] = $token;
    }
    return (string)(($_SESSION[ServerRuntimeBridge::CSRF_KEY] ?? ""));
  }
  public function requireCsrf(): void {
    $token = (string)(($_POST["csrf"] ?? ""));
    if ($token === "" || !hash_equals($this->csrfToken(), $token)) {
      throw new RuntimeException("CSRF検証に失敗しました。");
    }
  }
  public function bootSession(): void {
    if (session_status() !== PHP_SESSION_ACTIVE) {
      $secure = ($_SERVER["HTTPS"] ?? "off") !== "off";
      $params = ['lifetime' => 1800, 'httponly' => true, 'samesite' => "Strict", 'secure' => $secure, ];
      ini_set("session.use_strict_mode", "1");
      session_name("adlaire_studio");
      session_set_cookie_params($params);
      session_start();
    }
  }
  public function login(string $username): void {
    $_SESSION["admin"] = $username;
    $_SESSION["authenticated_at"] = time();
  }
  public function logout(): void {
    unset($_SESSION["admin"]);
    unset($_SESSION["authenticated_at"]);
    session_destroy();
  }
  public function redirect(string $to): void {
    header("Location: {$to}");
  }
  public function json(mixed $payload): void {
    http_response_code(200);
    header("Content-Type: application/json; charset=utf-8");
    echo json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?: '{"ok":false,"error":"JSON応答を生成できません。"}';
  }
  public function getAction(): string {
    return (string)(($_GET["action"] ?? "index"));
  }
  public function boundedCount(mixed $value): int|float {
    return max(0, (int)($value));
  }
  public function trimSlashes(string $value): string {
    return trim($value, "/");
  }
}
