<?php
/* Generated by PhpTranspiler pt.0.59. Source: server-wide-syntax.input.ts. */
final class ServerWideSyntaxBridge {
  public function firstPair(mixed $values): string {
    [$first, $second] = $values;
    return $first + $second;
  }
  public function userLabel(mixed $user): string {
    ['username' => $username, 'role' => $userRole] = $user;
    return $username . ":" . $userRole;
  }
  public function mergedValues(mixed $base, string $extra): mixed {
    return array_merge($base, [$extra]);
  }
  public function mergedRecord(mixed $base, string $status): mixed {
    return array_merge($base, ['status' => $status]);
  }
  public function sumValues(array $values): int|float {
    return array_reduce($values, fn($left, $right) => $left + $right, 0);
  }
  public function sortByOrder(mixed $items): mixed {
    usort($items, fn($left, $right): int => $left['order'] <=> $right['order']);
    return $items;
  }
  public function sortSimple(mixed $values): mixed {
    sort($values);
    return $values;
  }
  public function statusLabel(string $status): string {
    return match ($status) { "draft" => "下書き", "published" => "公開", default => "不明" };
  }
  public function present(mixed $record): bool {
    return isset($record["title"]) && !empty($record["title"]);
  }
  public function objectMethodValues(mixed $siteSettings, mixed $navigation, mixed $adSlots, string $sourcePath): mixed {
    $title = $siteSettings->pageTitle($sourcePath);
    $nav = $navigation->enabled();
    $slots = $adSlots->enabled();
    return ['title' => $title, 'nav' => $nav, 'slots' => $slots];
  }
  public function indexedPush(mixed $report, mixed $item): mixed {
    $report["items"][] = $item;
    return $report;
  }
  public function replaceExtension(string $sourcePath): string {
    return str_replace(".md", ".html", $sourcePath);
  }
}
