<?php
/* Generated by PhpTranspiler pt.0.59. Source: server-io.input.ts. */
final class ServerIoBridge {
  public function sanitize(mixed $value): string {
    if (!is_string($value)) {
      return "";
    }
    $trimmed = trim((string)($value));
    return htmlspecialchars($trimmed, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8");
  }
  public function renderMultiline(string $content): string {
    return nl2br(htmlspecialchars($content, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8"));
  }
  public function decodePayload(string $bytes): mixed {
    return json_decode($bytes, true);
  }
  public function encodePayload(mixed $payload): string {
    return json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
  }
  public function encodePrettyPayload(mixed $payload): string {
    return json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
  }
  public function imageData(string $bytes): string {
    return base64_encode($bytes);
  }
  public function decodeImageData(string $bytes): string {
    return base64_decode($bytes);
  }
  public function lines(string $markdown): mixed {
    return preg_split("/\\R/", $markdown);
  }
  public function writeHtml(string $html): void {
    echo $html;
  }
  public function validUrl(string $url): bool {
    return filter_var($url, FILTER_VALIDATE_URL) !== false;
  }
  public function validEmail(string $value): bool {
    return filter_var($value, FILTER_VALIDATE_EMAIL) !== false;
  }
  public function normalizePath(string $path): string {
    return ltrim(rtrim($path, "/"), "/");
  }
  public function listEntries(string $root): mixed {
    if (!is_dir($root)) {
      return [];
    }
    $entries = scandir($root);
    if (!is_array($entries)) {
      return [];
    }
    return $entries;
  }
  public function prepareTarget(string $target): void {
    $directory = dirname($target);
    if (!is_dir($directory)) {
      mkdir($directory, 493, true);
    }
  }
  public function moveFile(string $source, string $target): bool {
    if (!is_file($source) && !is_link($source)) {
      return false;
    }
    $name = basename($target);
    $parent = dirname($target);
    if ($name === "" || !is_dir($parent)) {
      return false;
    }
    return rename($source, $target);
  }
  public function copyFile(string $source, string $target): bool {
    return copy($source, $target);
  }
  public function removePath(string $path): bool {
    if (is_dir($path)) {
      return rmdir($path);
    }
    if (is_file($path) || is_link($path)) {
      return unlink($path);
    }
    return true;
  }
  public function noUploadFile(mixed $file): bool {
    return array_key_exists("error", $file) && $file["error"] === UPLOAD_ERR_NO_FILE;
  }
  public function numericOrder(mixed $value): bool {
    return is_int($value) || (is_string($value) && ctype_digit($value));
  }
  public function failForbidden(): void {
    http_response_code(403);
    exit;
  }
}
