<?php
/* Generated by PhpTranspiler pt.0.59. Source: server-migration-critical.input.ts. */
final class StaticResult {
  public function __construct(public readonly string $language) {
  }
}
final class StaticResultFactory {
  public static function make(): StaticResult {
    return new StaticResult("ja");
  }
}
final class ServerMigrationCriticalBridge {
  public function normalizeMarkdownPath(string $path): string {
    return preg_replace("/\\.md$/", ".html", $path);
  }
  private function versionNumber(string $version): string {
    return $version;
  }
  public function normalizeAction(string $action): string {
    return match ($action) { "before", "main_before", "before_content" => "before", "after", "main_after", "after_content" => "after", "logic" => throw new LogicException("論理的に到達しないactionです。"), default => throw new InvalidArgumentException("未対応のactionです。") };
  }
  public function normalizeUsers(mixed $users): mixed {
    return array_map(fn($user) => ['username' => (string)($user["username"] ?? ""), 'role' => (string)($user["role"] ?? ""), 'created_at' => (string)($user["created_at"] ?? ""), ], $users);
  }
  public function allowedRole(string $role): bool {
    return in_array($role, ["admin", "editor"], true);
  }
  public function workItemPath(mixed $item): string {
    return $item->getPathname();
  }
  public function encodedPath(string $path): string {
    return rawurlencode($path);
  }
  public function sortByPath(mixed $items): mixed {
    usort($items, fn($left, $right): int => strcmp($left['path'], $right['path']));
    return $items;
  }
  public function sortByPublishedAtDesc(mixed $items): mixed {
    usort($items, fn($left, $right): int => strcmp($right['publishedAt'], $left['publishedAt']));
    return $items;
  }
  public function sortByVersionDesc(mixed $items): mixed {
    usort($items, fn($left, $right): int => version_compare($this->versionNumber((string)($right["version"] ?? "")), $this->versionNumber((string)($left["version"] ?? ""))));
    return $items;
  }
  public function blockMap(array $values): array {
    return array_map(fn($value) => trim($value), $values);
  }
  public function dateAtom(string $value): string {
    $published = new DateTimeImmutable($value);
    return $published->format(DATE_ATOM);
  }
  public function currentTimestamp(): int|float {
    return time();
  }
  public function zipManifest(string $path): bool {
    $archive = new ZipArchive();
    $archive->open($path, ZipArchive::CREATE);
    $archive->addFromString("manifest.json", "{}");
    $archive->close();
    return true;
  }
  public function fetchText(string $url): string {
    $handle = curl_init($url);
    curl_setopt($handle, CURLOPT_RETURNTRANSFER, true);
    $body = curl_exec($handle);
    unset($handle);
    return (string)($body);
  }
  public function forwardCompatibleLibraryHelpers(string $value, int|float $timestamp): mixed {
    $trimmed = mb_trim($value);
    $title = mb_ucfirst($trimmed);
    $next = str_increment("az");
    $headers = http_get_last_response_headers();
    http_clear_last_response_headers();
    $created = DateTimeImmutable::createFromTimestamp($timestamp);
    $micros = $created->getMicrosecond();
    $created->setMicrosecond($micros);
    return ['title' => $title, 'next' => $next, 'headers' => $headers, 'micros' => $micros];
  }
  public function parsedRequestBody(): mixed {
    return request_parse_body();
  }
  public function php84LibraryHelpers(string $value, string $decimal, mixed $reflectionConstant, mixed $reflectionProperty, mixed $generator): mixed {
    $rounded = bcround($decimal, 2);
    $ceiling = bcceil($decimal);
    $floor = bcfloor($decimal);
    $pair = bcdivmod($decimal, "2");
    $ieee = fpow(0, -2);
    $graphemes = grapheme_str_split($value);
    $reader = XMLReader::fromString("<root />");
    $writer = XMLWriter::toMemory();
    $allFilled = array_all([$value], fn($entry): bool => $entry !== "");
    $anyFilled = array_any([$value], fn($entry): bool => $entry !== "");
    $found = array_find([$value], fn($entry): bool => $entry !== "");
    $foundKey = array_find_key([$value], fn($entry): bool => $entry !== "");
    return ['rounded' => $rounded, 'ceiling' => $ceiling, 'floor' => $floor, 'pair' => $pair, 'ieee' => $ieee, 'graphemes' => $graphemes, 'reader' => $reader, 'writer' => $writer, 'allFilled' => $allFilled, 'anyFilled' => $anyFilled, 'found' => $found, 'foundKey' => $foundKey, 'deprecated' => $reflectionConstant->isDeprecated(), 'dynamic' => $reflectionProperty->isDynamic(), 'closed' => $generator->isClosed(), ];
  }
  public function php84ExtensionHelpers(mixed $domNode, mixed $otherDomNode, mixed $xpath, mixed $timezone, mixed $formatter, mixed $calendar, mixed $storage, mixed $soapServer, mixed $tidyNode, mixed $xslt): mixed {
    $position = $domNode->compareDocumentPosition($otherDomNode);
    $disconnected = Dom\Node::DOCUMENT_POSITION_DISCONNECTED;
    $preceding = Dom\Node::DOCUMENT_POSITION_PRECEDING;
    $following = Dom\Node::DOCUMENT_POSITION_FOLLOWING;
    $contains = Dom\Node::DOCUMENT_POSITION_CONTAINS;
    $containedBy = Dom\Node::DOCUMENT_POSITION_CONTAINED_BY;
    $selected = $domNode->querySelector("main > article.featured");
    $selectedAll = $domNode->querySelectorAll("article");
    $classList = $otherDomNode->classList;
    $featured = $classList->contains("featured");
    $quoted = DOMXPath::quote("value");
    $xpath->registerPhpFunctionNS("urn:adlaire", "format", "format_callback");
    $iana = $timezone->getIanaID();
    $parsed = $formatter->parseToCalendar("2026-08-16");
    $gregorianDate = IntlGregorianCalendar::createFromDate(2026, 7, 16);
    $gregorianDateTime = IntlGregorianCalendar::createFromDateTime(2026, 7, 16, 10, 30, 0);
    $storage->seek(0);
    $soapResponse = $soapServer->__getLastResponse();
    $nextSibling = $tidyNode->getNextSibling();
    $previousSibling = $tidyNode->getPreviousSibling();
    $xslt->registerPhpFunctionNS("urn:adlaire", "render", "render_callback");
    return ['position' => $position, 'disconnected' => $disconnected, 'preceding' => $preceding, 'following' => $following, 'contains' => $contains, 'containedBy' => $containedBy, 'selected' => $selected, 'selectedAll' => $selectedAll, 'featured' => $featured, 'quoted' => $quoted, 'iana' => $iana, 'parsed' => $parsed, 'gregorianDate' => $gregorianDate, 'gregorianDateTime' => $gregorianDateTime, 'soapResponse' => $soapResponse, 'nextSibling' => $nextSibling, 'previousSibling' => $previousSibling];
  }
  public function php84ClassAndConstantHelpers(string $path, mixed $reflector, mixed $initializer, mixed $lazyObject, mixed $property): mixed {
    $amount = new BcMath\Number("12.34");
    $connected = PDO::connect("sqlite:" . $path);
    $sqliteDriver = new Pdo\Sqlite("sqlite:" . $path);
    $ghost = $reflector->newLazyGhost($initializer);
    $uninitialized = $reflector->isUninitializedLazyObject($ghost);
    $reflector->initializeLazyObject($ghost);
    $reflector->markLazyObjectAsInitialized($ghost);
    $reflector->resetAsLazyGhost($lazyObject, $initializer);
    $property->skipLazyInitialization($lazyObject);
    $property->setRawValueWithoutLazyInitialization($lazyObject, "value");
    $rounded = round(1.5, 0, RoundingMode::HalfAwayFromZero);
    $backgroundQos = Pcntl\QosClass::Background;
    $mysqlDriver = new Pdo\Mysql("mysql:host=localhost");
    $pgsqlDriver = new Pdo\Pgsql("pgsql:host=localhost");
    $odbcDriver = new Pdo\Odbc("odbc:adlaire");
    $dbLibDriver = new Pdo\DbLib("dblib:host=localhost");
    $firebirdDriver = new Pdo\Firebird("firebird:dbname=localhost:/tmp/adlaire.fdb");
    $html = Dom\HTMLDocument::createFromString("<main></main>");
    $xml = Dom\XMLDocument::createFromString("<root />");
    $reflectedConstant = new ReflectionConstant("PHP_VERSION");
    $reflectedConstantName = $reflectedConstant->getName();
    $reflectedConstantValue = $reflectedConstant->getValue();
    $reflectedConstantDeprecated = $reflectedConstant->isDeprecated();
    return ['amount' => $amount, 'connected' => $connected, 'sqliteDriver' => $sqliteDriver, 'mysqlDriver' => $mysqlDriver, 'pgsqlDriver' => $pgsqlDriver, 'odbcDriver' => $odbcDriver, 'dbLibDriver' => $dbLibDriver, 'firebirdDriver' => $firebirdDriver, 'uninitialized' => $uninitialized, 'rounded' => $rounded, 'backgroundQos' => $backgroundQos, 'html' => $html, 'xml' => $xml, 'reflectedConstant' => $reflectedConstant, 'reflectedConstantName' => $reflectedConstantName, 'reflectedConstantValue' => $reflectedConstantValue, 'reflectedConstantDeprecated' => $reflectedConstantDeprecated, 'curl' => curl_version(), 'phpOutput' => PHP_OUTPUT_HANDLER_PROCESSED, 'phpSbin' => PHP_SBINDIR, 'curlHttp3' => CURL_HTTP_VERSION_3, 'curlPrereqOk' => CURL_PREREQFUNC_OK, 'libxmlNoXxe' => LIBXML_NO_XXE, 'pgChunk' => PGSQL_TUPLES_CHUNK, 'tokenizer' => T_PUBLIC_SET, 'xmlHuge' => XML_OPTION_PARSE_HUGE, 'zipTruncated' => ZipArchive::ER_TRUNCATED_ZIP, ];
  }
  public function php84MetadataAndStreamHelpers(): mixed {
    $deprecated = new Deprecated("Use replacement", "pt.0.59");
    $parseError = new RequestParseBodyException("multipart parse failed");
    $soapUrl = new Soap\Url("https://example.test/service");
    $soapSdl = new Soap\Sdl("https://example.test/service.wsdl");
    $bucket = new StreamBucket();
    $bucket->data = "payload";
    $bucketData = $bucket->data;
    $bucketLength = $bucket->datalen;
    return ['deprecated' => $deprecated, 'parseError' => $parseError, 'soapUrl' => $soapUrl, 'soapSdl' => $soapSdl, 'bucketData' => $bucketData, 'bucketLength' => $bucketLength];
  }
  public function php84CryptoCurlAndXslHelpers(mixed $xslt, mixed $keyConfig, mixed $signature): mixed {
    $pkey = openssl_pkey_new($keyConfig);
    $pkeyDetails = openssl_pkey_get_details($pkey);
    $signed = openssl_sign("payload", $signature, $pkey, OPENSSL_ALGO_SHA256);
    $verified = openssl_verify("payload", $signature, $pkey, OPENSSL_ALGO_SHA256);
    $argonProvider = PASSWORD_ARGON2_PROVIDER;
    $postTransferInfo = CURLINFO_POSTTRANSFER_TIME_T;
    $responseTimeoutOption = CURLOPT_SERVER_RESPONSE_TIMEOUT;
    $xslt->maxTemplateDepth = 200;
    $xslt->maxTemplateVars = 100;
    $maxDepth = $xslt->maxTemplateDepth;
    $maxVars = $xslt->maxTemplateVars;
    return ['pkey' => $pkey, 'pkeyDetails' => $pkeyDetails, 'signed' => $signed, 'verified' => $verified, 'argonProvider' => $argonProvider, 'postTransferInfo' => $postTransferInfo, 'responseTimeoutOption' => $responseTimeoutOption, 'maxDepth' => $maxDepth, 'maxVars' => $maxVars];
  }
  public function php84ReflectionHookAndConstantHelpers(mixed $property, mixed $targetObject): mixed {
    $getHookType = PropertyHookType::Get;
    $setHookType = PropertyHookType::Set;
    $getHook = $property->getHook($getHookType);
    $hooks = $property->getHooks();
    $hasGetHook = $property->hasHook($getHookType);
    $hasHooks = $property->hasHooks();
    $rawValue = $property->getRawValue($targetObject);
    $settableType = $property->getSettableType();
    $abstractProperty = $property->isAbstract();
    $finalProperty = $property->isFinal();
    $lazyProperty = $property->isLazy($targetObject);
    $privateSet = $property->isPrivateSet();
    $protectedSet = $property->isProtectedSet();
    $virtualProperty = $property->isVirtual();
    return ['getHookType' => $getHookType, 'setHookType' => $setHookType, 'getHook' => $getHook, 'hooks' => $hooks, 'hasGetHook' => $hasGetHook, 'hasHooks' => $hasHooks, 'rawValue' => $rawValue, 'settableType' => $settableType, 'abstractProperty' => $abstractProperty, 'finalProperty' => $finalProperty, 'lazyProperty' => $lazyProperty, 'privateSet' => $privateSet, 'protectedSet' => $protectedSet, 'virtualProperty' => $virtualProperty];
  }
  public function php84AdditionalConstantHelpers(): mixed {
    return ['curlDebug' => CURLOPT_DEBUGFUNCTION, 'curlHeaderIn' => CURLINFO_HEADER_IN, 'curlHttp3Only' => CURL_HTTP_VERSION_3ONLY, 'curlPrereq' => CURLOPT_PREREQFUNCTION, 'curlSslIn' => CURLINFO_SSL_DATA_IN, 'curlSslOut' => CURLINFO_SSL_DATA_OUT, 'curlKeepCount' => CURLOPT_TCP_KEEPCNT, 'intlPattern' => IntlDateFormatter::PATTERN, 'intlUnary' => IntlChar::PROPERTY_IDS_UNARY_OPERATOR, 'intlCompatStart' => IntlChar::PROPERTY_ID_COMPAT_MATH_START, 'intlCompatContinue' => IntlChar::PROPERTY_ID_COMPAT_MATH_CONTINUE, 'intlRoundHalfOdd' => NumberFormatter::ROUND_HALFODD, 'ldapTlsMax' => LDAP_OPT_X_TLS_PROTOCOL_MAX, 'ldapTls13' => LDAP_OPT_X_TLS_PROTOCOL_TLS1_3, 'ocspPurpose' => X509_PURPOSE_OCSP_HELPER, 'timestampPurpose' => X509_PURPOSE_TIMESTAMP_SIGN, 'sodiumAegis128' => SODIUM_CRYPTO_AEAD_AEGIS128L_KEYBYTES, 'sodiumAegis128Auth' => SODIUM_CRYPTO_AEAD_AEGIS128L_ABYTES, 'sodiumAegis128Nonce' => SODIUM_CRYPTO_AEAD_AEGIS128L_NPUBBYTES, 'sodiumAegis128Secret' => SODIUM_CRYPTO_AEAD_AEGIS128L_NSECBYTES, 'sodiumAegis256' => SODIUM_CRYPTO_AEAD_AEGIS256_KEYBYTES, 'sodiumAegis256Auth' => SODIUM_CRYPTO_AEAD_AEGIS256_ABYTES, 'sodiumAegis256Nonce' => SODIUM_CRYPTO_AEAD_AEGIS256_NPUBBYTES, 'sodiumAegis256Secret' => SODIUM_CRYPTO_AEAD_AEGIS256_NSECBYTES, ];
  }
  public function php84SodiumAegisHelpers(string $message, string $additionalData, string $nonce128, string $nonce256): mixed {
    $key128 = sodium_crypto_aead_aegis128l_keygen();
    $encrypted128 = sodium_crypto_aead_aegis128l_encrypt($message, $additionalData, $nonce128, $key128);
    $decrypted128 = sodium_crypto_aead_aegis128l_decrypt($encrypted128, $additionalData, $nonce128, $key128);
    $key256 = sodium_crypto_aead_aegis256_keygen();
    $encrypted256 = sodium_crypto_aead_aegis256_encrypt($message, $additionalData, $nonce256, $key256);
    $decrypted256 = sodium_crypto_aead_aegis256_decrypt($encrypted256, $additionalData, $nonce256, $key256);
    return ['key128' => $key128, 'encrypted128' => $encrypted128, 'decrypted128' => $decrypted128, 'key256' => $key256, 'encrypted256' => $encrypted256, 'decrypted256' => $decrypted256];
  }
  public function php84HashContextHelpers(mixed $hashContext): mixed {
    return $hashContext->__debugInfo();
  }
  public function php84DbaAndOdbcHelpers(string $path): mixed {
    $dba = dba_open($path, "c", "flatfile");
    dba_replace("site", "Adlaire", $dba);
    $dbaValue = dba_fetch("site", $dba);
    $dbaExists = dba_exists("site", $dba);
    $dbaFirst = dba_firstkey($dba);
    $dbaNext = dba_nextkey($dba);
    dba_sync($dba);
    dba_close($dba);
    $connection = odbc_connect("adlaire", "", "");
    $result = odbc_exec($connection, "SELECT 1 AS value");
    $row = odbc_fetch_array($result);
    $objectRow = odbc_fetch_object($result);
    $error = odbc_error($connection);
    $message = odbc_errormsg($connection);
    odbc_close($connection);
    return ['dbaValue' => $dbaValue, 'dbaExists' => $dbaExists, 'dbaFirst' => $dbaFirst, 'dbaNext' => $dbaNext, 'row' => $row, 'objectRow' => $objectRow, 'error' => $error, 'message' => $message];
  }
  public function sqliteDefaultDatabase(string $path): mixed {
    $db = new PDO('sqlite:' . $path, null, null, []);
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $db->exec("CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)");
    $statement = $db->prepare("INSERT INTO settings (key, value) VALUES (:key, :value)");
    $statement->bindValue(":key", "site_name", PDO::PARAM_STR);
    $statement->bindValue(":value", "Adlaire", PDO::PARAM_STR);
    $statement->execute();
    $rows = $db->query("SELECT key, value FROM settings")->fetchAll(PDO::FETCH_ASSOC);
    return ['rows' => $rows, 'lastId' => $db->lastInsertId()];
  }
  public function sqlite3ExtensionDatabase(string $path): mixed {
    SQLite3::enableExceptions(true);
    $db = new SQLite3($path);
    $db->busyTimeout(5000);
    $db->exec("CREATE TABLE IF NOT EXISTS cache (key TEXT PRIMARY KEY, value TEXT NOT NULL)");
    $statement = $db->prepare("INSERT OR REPLACE INTO cache (key, value) VALUES (:key, :value)");
    $statement->bindValue(":key", "home", SQLITE3_TEXT);
    $statement->bindValue(":value", SQLite3::escapeString("ok"), SQLITE3_TEXT);
    $result = $statement->execute();
    $row = $db->querySingle("SELECT value FROM cache WHERE key = 'home'", true);
    $changes = $db->changes();
    $result->finalize();
    $db->close();
    return ['row' => $row, 'changes' => $changes, 'version' => SQLite3::version()];
  }
  public function uploadFile(): mixed {
    $file = ($_FILES["content_file"] ?? null);
    if (!is_array($file) || ($file["error"] ?? UPLOAD_ERR_NO_FILE) === UPLOAD_ERR_NO_FILE) {
      return null;
    }
    $tmpName = (string)($file["tmp_name"] ?? "");
    if (!is_uploaded_file($tmpName)) {
      throw new UnexpectedValueException("アップロードファイルではありません。");
    }
    return ["tmp_name" => $tmpName, 'originalName' => basename((string)($file["name"] ?? "")), ];
  }
  public function stringAndArrayHelpers(string $value, array $roles): mixed {
    $upper = strtoupper($value);
    $lower = strtolower($value);
    $length = strlen($value);
    $pieces = explode("/", $value);
    $uniqueRoles = array_values(array_unique($roles));
    return ['upper' => $upper, 'lower' => $lower, 'length' => $length, 'pieces' => $pieces, 'uniqueRoles' => $uniqueRoles, 'editorIndex' => array_search("editor", $uniqueRoles, true), 'token' => bin2hex(random_bytes(4)), ];
  }
  public function directObjectArgument(string $theme, string $user): void {
    $this->record("theme.save", ['theme' => $theme, 'user' => $user]);
  }
  public function staticResultProperty(): string {
    return StaticResultFactory::make()->language;
  }
  public function methodResultLength(): int|float {
    return count($this->values());
  }
  private function values(): array {
    return [];
  }
  private function record(string $type, mixed $data): void {
    echo $type;
  }
}
final class ZipBinaryBridge {
  public function zipBinary(string $bytes): mixed {
    $offset = strrpos($bytes, "PK\x05\x06");
    if ($offset === false) {
      throw new RuntimeException("zipが不正です。");
    }
    $length = strlen($bytes);
    $data = unpack("v", substr($bytes, (int)($offset) + 10, 2));
    $inflated = gzinflate(substr($bytes, 0, $length));
    if ($inflated === false) {
      throw new RuntimeException("zip展開に失敗しました。");
    }
    return $data;
  }
}
final class ServerFoundationCompletionBridge {
  public function htmlSafety(string $value, string $content, string $reason): string {
    $label = $reason !== "" ? "対象 / " . $reason : "対象";
    return '<div class="notice">' . htmlspecialchars($label, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8") . '</div>' . nl2br(htmlspecialchars($content, ENT_QUOTES | ENT_SUBSTITUTE, "UTF-8"));
  }
  public function requestPayload(): mixed {
    $title = ($_POST["title"] ?? "");
    $draft = isset($_POST["draft"]);
    $file = ($_FILES["content_file"] ?? null);
    $bytes = file_get_contents('php://input');
    if (is_array($file)) {
      $tmpName = (string)($file["tmp_name"] ?? "");
      if ($tmpName !== "" && is_uploaded_file($tmpName)) {
        return file_get_contents($tmpName);
      }
    }
    return ['title' => $title, 'draft' => $draft, 'bytes' => $bytes];
  }
  public function arrayForms(mixed $items): mixed {
    while (count($items) < 5) {
      $items[] = ['label' => "", 'order' => count($items), 'enabled' => false];
    }
    $normalized = [];
    foreach ($items as $index => $item) {
      $normalized[] = ['index' => $index, 'label' => (string)($item["label"] ?? "")];
    }
    return array_values($normalized);
  }
  public function staticPublisherHelpers(mixed $articles): mixed {
    $groups = [];
    $map = [];
    foreach ($articles as $article) {
      if (!($article instanceof ArticleContract)) {
        continue;
      }
      if (!$article->publicEligible) {
        continue;
      }
      $groups[$article->routeBase][] = $article;
      $outputRecord = ['direct' => [$article->outputPath], 'indirect' => [rtrim($article->routeBase, "/") . "/index.html"], ];
      $map[$article->id] = $outputRecord;
    }
    ksort($map);
    foreach ($groups as $routeBase => $items) {
      usort($items, fn($left, $right): int => strcmp($right->publishedAt, $left->publishedAt));
      if (str_starts_with($routeBase, "articles") && !str_ends_with($routeBase, "/")) {
        $map[$routeBase] = preg_replace("/\\.md$/", ".html", ltrim($routeBase, "/"));
      }
    }
    return $map;
  }
  public function persistence(string $path, mixed $payload): string {
    if (!is_file($path)) {
      file_put_contents($path, "{}", LOCK_EX);
    }
    $bytes = json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    if ($bytes === false || file_put_contents($path, $bytes, LOCK_EX) === false) {
      throw new RuntimeException("保存できません。");
    }
    $readBack = file_get_contents($path);
    if ($readBack === false || !hash_equals(hash("sha256", $bytes), hash("sha256", $readBack))) {
      throw new RuntimeException("保全確認に失敗しました。");
    }
    return gmdate(DATE_ATOM, (int)(strtotime("2026-08-16T00:00:00+00:00")));
  }
}
