<?php
/* Generated by PhpTranspiler pt.0.59. Source: server-files.input.ts. */
final class ServerFileBridge {
  public function ensureMarker(string $path): bool {
    if (!file_exists($path)) {
      return touch($path);
    }
    clearstatcache(true, $path);
    return is_file($path) && is_readable($path) && is_writable($path);
  }
  public function byteSize(string $path): int|float {
    if (!is_file($path)) {
      return 0;
    }
    return (float)(filesize($path));
  }
  public function collect(mixed $runtime): mixed {
    $values = [];
    foreach ($runtime->files() as $item) {
      $values[] = $item;
    }
    foreach ($runtime->map() as $key => $_value) {
      $values[] = $key;
    }
    return $values;
  }
}
