<?php
/* Generated by PhpTranspiler pt.0.59. Source: server-workdata.input.ts. */
final class ServerWorkDataBridge {
  public function __construct(private readonly string $workRoot) {
  }
  public function cleanup(): void {
    try {
      foreach (new FilesystemIterator($this->workRoot, FilesystemIterator::SKIP_DOTS) as $item) {
        if ($item->getFilename() === ".gitignore") {
          continue;
        }
        if (!$this->deletePath($item->getPathname())) {
          throw new RuntimeException("作業データの削除に失敗しました。");
        }
      }
    } catch (Throwable) {
      throw new RuntimeException("作業データを確認できません。");
    }
  }
  private function deletePath(string $path): bool {
    if (is_file($path) || is_link($path)) {
      return unlink($path);
    }
    if (is_dir($path)) {
      foreach (new FilesystemIterator($path, FilesystemIterator::SKIP_DOTS) as $child) {
        if (!$this->deletePath($child->getPathname())) {
          return false;
        }
      }
      return rmdir($path);
    }
    return true;
  }
  public function moveUpload(string $source, string $target): bool {
    return move_uploaded_file($source, $target);
  }
  public function modifiedAt(string $path): int|float {
    if (!file_exists($path)) {
      return 0;
    }
    return (float)(filemtime($path));
  }
  public function matches(string $pattern): mixed {
    $files = glob($pattern);
    if (!is_array($files)) {
      return [];
    }
    return $files;
  }
  public function jsonErrorMessage(): string {
    return json_last_error_msg();
  }
  public function caughtMessage(mixed $error): string {
    return $error->getMessage();
  }
}
