<?php
/* Generated by PhpTranspiler pt.0.59. Source: server-predicates.input.ts. */
final class ServerPredicateBridge {
  public function hasAdministrator(mixed $users): bool {
    return count(array_filter($users, fn($user) => $user["role"] === "admin")) > 0;
  }
  public function allEnabled(mixed $users): bool {
    return count(array_filter($users, fn($user) => $user["enabled"] === true)) === count($users);
  }
  public function findUser(mixed $users, string $username): mixed {
    return (array_values(array_filter($users, fn($user) => $user["username"] === $username))[0] ?? null);
  }
  public function userIndex(mixed $users, string $username): int|float {
    return (array_search(true, array_map(fn($user) => $user["username"] === $username, $users), true) === false ? -1 : array_search(true, array_map(fn($user) => $user["username"] === $username, $users), true));
  }
}
