<?php
/* Generated by PhpTranspiler pt.0.59. Source: statements.input.ts. */
function normalizeName(string $value): string {
  return trim($value);
}
final class StatementTarget {
  public function touch(string $value): void {
    $this->record($value);
  }
  private function record(string $value): void {
    return;
  }
}
final class StatementUsage {
  public function run(StatementTarget $target, string $value): string {
    $target->touch($value);
    StatementUsage::report($value);
    normalizeName($value);
    try {
      $target->touch("try");
    } catch (Throwable $error) {
      $target->touch("catch");
    } finally {
      $target->touch("finally");
    }
    return $value;
  }
  public static function report(string $value): void {
    return;
  }
}
