<?php
/* Generated by PhpTranspiler pt.0.59. Source: static.input.ts. */
final class PathTool {
  public static function join(string $left, string $right): string {
    return "{$left}/{$right}";
  }
}
final class StaticUsage {
  public function make(string $name): string {
    return PathTool::join("root", $name);
  }
}
final class StaticCache {
  private static mixed $cache = [];
  public static function remember(string $key, string $value): string {
    if (array_key_exists($key, self::$cache)) {
      return (string)(self::$cache[$key]);
    }
    self::$cache[$key] = $value;
    return $value;
  }
  public static function clear(): void {
    StaticCache::$cache = [];
  }
}
