<?php
/* Generated by PhpTranspiler pt.0.59. Source: switch-flow.input.ts. */
final class SwitchFlow {
  public function resolve(array $values, string $mode, string $fallback): string {
    $selected = $fallback;
    foreach ($values as $value) {
      if ($value === "") {
        continue;
      }
      switch ($mode) {
        case "first":
          $selected = $value;
          break;
        case $fallback:
          $selected = $fallback;
          break;
        default:
          $selected = trim($value);
          break;
      }
      break;
    }
    return $selected;
  }
}
