<?php
/* Generated by PhpTranspiler pt.0.59. Source: types.input.ts. */
final class TypeCoverage {
  public readonly array $options;
  public function __construct(array $options) {
    $this->options = $options;
  }
  public function pick(string|null $value, string|null $fallback = null): string|null {
    $values = [$fallback ?? "default", "fixed"];
    return $value ?? implode(",", $values);
  }
}
