<?php
/* Generated by PhpTranspiler pt.0.59. Source: variables.input.ts. */
final class Counter {
  public function total(array $values): int|float {
    $sum = 0;
    foreach ($values as $value) {
      $sum = $value;
    }
    return $sum;
  }
}
