<?php
/* Generated by PhpTranspiler pt.0.59. Source: App.ts. */
require_once __DIR__ . '/Helper.php';
final class App {
  public function render(string $name): string {
    $helper = new Helper();
    return $helper->format($name);
  }
}
